---
title: "Media"
---

<h2> Op-Eds, Columns, and Policy Briefs</h2>

<div class="divmedia">

<a target="_blank" href="https://blogs.lse.ac.uk/businessreview/2022/11/29/the-us-eu-gap-predistribution-plays-a-key-role-in-moderating-income-inequality/">The US-EU Gap: Predistribution Plays a Key Role in Moderating Income Inequality</a>, <b>LSE Business Review</b>, 2022.

<a target="_blank" href="https://agendapublica.elpais.com/noticia/17907/radical-right-voting-and-new-dividing-lines-of-french-politics">Radical Right Voting and the New Dividing Lines of French Politics</a>, <b>Agenda Pública</b>, 19/04/2022. <a target="_blank" href="https://agendapublica.elpais.com/noticia/17914/voto-derecha-radical-nuevas-lineas-divisorias-politica-francesa">[Spanish version]</a>

<a target="_blank" href="https://culturico.com/2022/02/14/south-africa-how-extreme-inequality-persists/">South Africa: How extreme inequality persists</a>, <b>Culturico</b>, 15/02/2022.

<a target="_blank" href="https://cepr.org/voxeu/columns/forty-years-inequality-europe-evidence-distributional-national-accounts">Forty years of inequality in Europe: Evidence from distributional national accounts</a> (with T. Blanchet & L. Chancel), <b>VoxEU</b>.

<a target="_blank" href="https://cepr.org/voxeu/columns/taxing-wealth-context-extreme-inequality-legacy-case-south-africa">Taxing wealth in a context of extreme inequality legacy: The case of South Africa</a> (with A. Chatterjee & L. Czajka), <b>VoxEU</b>.

<a target="_blank" href="https://soundcloud.com/ipea-online/podcast-series-deals-with-studies-related-to-wealth-tax?si=6737a1a83d1a4250becad3318878e25b&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing">Wealth tax: perspectives in a post-pandemic world</a>, <b>International Policy Center for Inclusive Growth</b>, 10/02/2022.

<a target="_blank" href="https://agendapublica.elpais.com/noticia/17271/clivajes-politicos-desigualdad-francia-voto-clase-populismo-elitismo">Clivajes políticos y desigualdad en Francia: ¿voto de clase, populismo o elitismo?</a>, <b>Agenda Pública</b>, 29/05/2021.

<a target="_blank" href="https://agendapublica.elpais.com/noticia/17343/clivajes-politicos-espana-edad-divide-mas-renta-educacion">Clivajes políticos en España: la edad divide más que la renta o la educación</a>, <b>Agenda Pública</b>, 20/04/2021.

<a target="_blank" href="https://www.dailymaverick.co.za/article/2021-01-31-is-a-wealth-tax-in-south-africa-really-a-bad-idea/">Is a wealth tax in South Africa really a bad idea?</a> (with A. Chatterjee & L. Czajka), <b>Business Maverick</b>, 31/01/2021.

<a target="_blank" href="https://theconversation.com/coronavirus-why-south-africa-needs-a-wealth-tax-now-137283?utm_source=twitter&utm_medium=bylinetwitterbutton">Coronavirus: Why South Africa Needs a Wealth Tax Now</a> (with A. Chatterjee & L. Czajka), <b>The Conversation</b>, 28/04/2020.

<a target="_blank" href="https://www.project-syndicate.org/commentary/europe-america-income-inequality-lessons-by-thomas-blanchet-et-al-2019-11">Why US Inequality Is Higher Than Europe’s</a> (with T. Blanchet & L. Chancel), <b>Project Syndicate</b>, 12/11/2019.

<a target="_blank" href="https://www.valor.com.br/opiniao/6339199/quem-interessa-aumentar-desigualdade?fbclid=IwAR1I6r6ESWiH0-5FFCzrQV1A9DKD69kxb13m7EOdWNE4J_PIKIsblwodzFI">A quem interessa aumentar a desigualdade?</a> (with T. Piketty, P. Zahluth Bastos, M. Morgan), <b>Valor Econômico</b>, 11/07/2019.

<a target="_blank" href="https://hdr.undp.org/content/how-did-europe-do-sdg-101-sustaining-income-growth-bottom-40">How did Europe do on SDG 10.1?</a> (with T. Blanchet & L. Chancel), <b>United Nations Development Programme</b>, 23/05/2019.

<a target="_blank" href="https://www.bangkokpost.com/opinion/opinion/1657564/thailands-democratic-foundations-remain-weak">Thailand's democratic foundations remain weak</a> (with T. Jenmana), <b>Bangkok Post</b>, 06/04/2019.

</div>






<h2> Interviews and Videos </h2>

<div class="divmedia">

<a target="_blank" href="https://www.france24.com/fr/%C3%A9missions/%C3%A9co-de-campagne/20220325-fiscalit%C3%A9-un-outil-d-efficacit%C3%A9-%C3%A9conomique-ou-de-justice-sociale?ref=tw">Fiscalité : un outil d'efficacité économique ou de justice sociale ?</a>, <b>France 24</b>, 03/2022.

<a target="_blank" href="https://www.youtube.com/watch?v=9eXhkXqHm9w">Inequality in South Africa: origins and solutions</a>, <b>World Inequality Lab</b>, 06/2022.

<a target="_blank" href="https://www.youtube.com/watch?v=t1h5HPaWYYs">How Culture War Kills Class Politics</a>, <b>Breaking Points</b>, 12/2021.

<a target="_blank" href="https://democracynerd.us/episode/episode-47-political-cleavages-social-inequalities-w-amory-gethin">Political Cleavages and Social Inequalities</a>, <b>Democracy Nerd</b>, 12/2021.

<a target="_blank" href="https://democracyparadox.com/2021/11/16/amory-gethin-on-political-cleavages-inequality-and-party-systems-in-50-democracies/">Political Cleavages, Inequality, and Party Systems in 50 Democracies</a>, <b>Democracy Paradox</b>, 11/2021.

<a target="_blank" href="https://www.liberation.fr/idees-et-debats/dans-un-systeme-ou-chaque-coalition-politique-represente-une-elite-les-electeurs-defavorises-se-sentent-exclus-20210505_4RWQDEURCZFS3POUBRD2V3FHOI/">Dans un système d’élites multiples, les électeurs défavorisés se sentent exclus</a>, <b>Libération</b>, 05/2021.

<a target="_blank" href="https://www.youtube.com/watch?v=TA4eG4b2ifY">Débat de l'égalité: Présentation de Clivages Politiques et Inégalités Sociales</a>, <b>World Inequality Lab</b>, 04/2021.

<a target="_blank" href="https://www.youtube.com/watch?v=ZoajQNg64DI&t=112s">Proposed wealth tax to assist with fiscal sustainability</a>, <b>SABC News</b>, 01/2021.

<a target="_blank" href="https://valor.globo.com/brasil/noticia/2018/11/06/classe-media-espremida-pesou-na-eleicao.ghtml">Classe média espremida pesou na eleição</a> (with M. Morgan), <b>Valor Econômico</b>, 11/2019.

<a target="_blank" href="https://www.youtube.com/watch?v=BamslhgQiXI&t=1s">Europe : 40 ans d'inégalités de revenus</a>, <b>France 24</b>, 04/2019.

<a target="_blank" href="https://bnr.bg/horizont/post/101102283/balgaria-e-sred-stranite-s-nai-golamo-neravenstvo-v-dohodite">България е сред страните с най-голямо неравенство в доходите</a>, <b>Bulgarian National Radio</b>, 04/2019.

</div>







<h2> In the News </h2>

<div class="divmedia">

<a target="_blank" href="https://www.washingtonpost.com/business/brazils-middle-class-isnt-buying-what-lulas-selling/2022/10/26/f4a04342-5519-11ed-ac8b-08bbfab1c5a5_story.html">Brazil’s Middle Class Isn’t Buying What Lula’s Selling</a>, <b>The Washington Post</b>, 10/2022.

<a target="_blank" href="https://www.latercera.com/la-tercera-domingo/noticia/francia-la-izquierda-ante-el-riesgo-de-la-irrelevancia-en-las-presidenciales/YDU22VW6JRALXAMGQ5WZQXXXSA/">Francia: La izquierda ante el riesgo de la irrelevancia en las presidenciales</a>, <b>La Tercera</b>, 01/2022.

<a target="_blank" href="https://www.zeit.de/zustimmung?url=https%3A%2F%2Fwww.zeit.de%2F2022%2F04%2Fsoziale-ungleichheit-spaltung-oekonomie-umweltschutz%2Fseite-2">Soziale Ungleichheit : Ideen gegen die Ungleichheit</a>, <b>Die Zeit</b>, 01/2022.

<a target="_blank" href="https://nadaesgratis.es/admin/izquierda-brahman-vs-derecha-mercader-divisiones-politicas-y-desigualdades-sociales">Izquierda Brahmán vs. Derecha Mercader: Divisiones Políticas y Desigualdades Sociales</a>, <b>Nada es Gratis</b>, 11/2021.

<a target="_blank" href="https://www.editionsbdl.com/produit/la-politique-des-classes-populaires/">Comment les partis de gauche sont devenus des "partis de diplômés"</a>, <b>Germinal</b>, 11/2021.

<a target="_blank" href="https://www.economist.com/middle-east-and-africa/2021/09/23/unpicking-inequality-in-south-africa">Not so black and white: Unpicking inequality in South Africa</a>, <b>The Economist</b>, 09/2021.

<a target="_blank" href="https://time.com/6087699/south-africa-wealth-gap-unchanged-since-apartheid/">South Africa Wealth Gap Unchanged Since Apartheid</a>, <b>Time</b>, 08/2021.

<a target="_blank" href="https://www.theguardian.com/commentisfree/2021/aug/05/around-the-world-the-disadvantaged-have-been-left-behind-by-politicians-of-all-hues">How politics became a contest dominated by two kinds of elite (with Martínez-Toledano & Piketty)</a>, <b>The Guardian</b>, 08/2021.

<a target="_blank" href="https://www.economist.com/graphic-detail/2021/05/29/educated-voters-leftward-shift-is-surprisingly-old-and-international">Educated voters’ leftward shift is surprisingly old</a>, <b>The Economist</b>, 05/2021.

<a target="_blank" href="https://www.lemonde.fr/idees/article/2021/05/03/pourquoi-les-pauvres-votent-ils-a-droite_6078884_3232.html">Pourquoi les pauvres votent-ils à droite ?</a>, <b>Le Monde</b>, 05/2021.

<a target="_blank" href="https://usbeketrica.com/fr/article/la-gauche-est-elle-vraiment-devenue-le-camp-des-elites-diplomees">La gauche est-elle vraiment devenue le camp des « élites diplômées » ?</a>, <b>Usbek & Rica</b>, 06/2021.

<a target="_blank" href="https://www.lamontagne.fr/paris-75000/actualites/les-classes-sociales-de-moins-en-moins-presentes-dans-les-urnes-selon-les-economistes-amory-gethin-et-thomas-piketty_13948359/">Les classes sociales de moins en moins présentes dans les urnes</a>, <b>La Montagne</b>, 05/2021.

<a target="_blank" href="https://www.groundup.org.za/article/15-sas-wealth-hands-just-3500-people-study-finds/">15% of South Africa's wealth is in the hands of just 3,500 people</a>, <b>GroundUp</b>, 03/2020.

<a target="_blank" href="https://www.expansion.com/economia/politica/2019/05/12/5cd2bade468aeba33e8b4610.html">El aumento de la desigualdad en España impulsa la inestabilidad política y el factor territorial</a>, <b>Expansión</b>, 05/2019.

<a target="_blank" href="https://www.eldiario.es/economia/izquierda-porcentuales-poblacion-educada-ochenta_1_1584545.html">La derecha atrae a cada vez más votantes con menores rentas y nivel educativo</a>, <b>El Diario</b>, 05/2019.

<a target="_blank" href="https://www.lemonde.fr/economie/article/2019/04/02/inegalites-les-ecarts-de-revenus-ont-augmente-partout-en-europe_5444517_3234.html">Inégalités : les écarts de revenus ont augmenté partout en Europe</a>, <b>Le Monde</b>, 04/2019.

<a target="_blank" href="https://www.tf1info.fr/international/france-europe-la-verite-sur-les-inegalites-2117284.html">France, Europe : la vérité sur les inégalités</a>, <b>LCI</b>, 04/2019.

<a target="_blank" href="https://kontrast.at/seit-40-jahren-waechst-die-untere-haelfte-der-einkommen-praktisch-nicht/?fbclid=IwAR1wLMWFezOnS2y3-CXWwKgTW6JCeWPqQNhXPTFidVzEHLKCwzTXw22bYNA">Seit 40 Jahren wachsen die Top-Einkommen doppelt so schnell wie die unteren</a>, <b>Kontrast</b>, 04/2019.

<a target="_blank" href="https://www.lemonde.fr/economie/article/2019/03/21/heurs-et-malheurs-de-la-gauche-eduquee_5439097_3234.html">Heurs et malheurs de la gauche éduquée</a>, <b>Le Monde</b>, 03/2019.

<a target="_blank" href="https://economictimes.indiatimes.com/news/elections/lok-sabha/india/polls-still-all-about-caste-religion/articleshow/68554634.cms?from=mdr">Polls still all about caste and religion</a>, <b>Economic Times</b>, 03/2019.

</div>










